version: 2.1

workflows:
  tests:
    jobs:
      - build-and-test

executors:
  docker-executor:
    docker:
      - image: circleci/python:3.7
    resource_class: medium

commands:
  setup_environment:
    steps:
      - run:
          name: "Install virtualenv, python 3.7 and required packages"
          command: |
            python -m virtualenv .env
            source .env/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
jobs:
  build-and-test:
    executor: docker-executor
    steps:
      - checkout
      - setup_environment
      - run:
          name: "Build baseline model"
          command: |
            source .env/bin/activate
            python test.py
